<MenuScreen>:
    name:'menu_screen'
    BoxLayout:
        orientation:'vertical'
        padding:dp(120),0,dp(120),dp(120)
        spacing:dp(40)
        Button:
            text:'ანდაზები'

        BoxLayout:
            orientation:'vertical'
            padding:dp(50),dp(20)
            spacing:dp(20)
            size_hint:1,None            
            height:dp(120)
            Label:
                text: f'აირჩიეთ რაუნდის ხანგრძლივობა'
                font_size: sp(12)
                halign: "center"
                size_hint:1, 0.2
                font_name:'DejaVuSans.ttf'#app.resource_path('assets/BPG2.ttf')
                valign: "middle"
                text_size: self.size
            Spinner:
                size_hint:1, 0.8
                text: "5:00"
                values: ["10:00", "5:00", "3:00" ]
                on_text: app.on_time_select(self.text)
                font_name:'assets/BPG2.ttf'

        BoxLayout:
            orientation:"vertical"
            spacing:dp(10)
            size_hint:1,None
            height:dp(200)
            Button:
                text:'თამაშის დაწყება'
                size_hint:1,None
                height:dp(100)
                on_release:app.sm.switch_to(app.game_screen)
                font_name:app.resource_path('assets/BPG2.ttf')
            Button:
                text:'ლიდერბორდი'
                size_hint:1,None
                height:dp(100)
                on_release:app.sm.switch_to(app.liderboard_screen)
                font_name:app.resource_path('assets/BPG2.ttf')